In [1]:
library(topGO)

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: graph

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: GO.db

Loading required package: AnnotationDbi

Loading required package: stats4

Loading required package: IRanges

Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:base’:

    expand.grid, I, unname




Loading required package: SparseM


Attaching package: ‘SparseM’


The following object is masked from ‘package:base’:

    backsolve



groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.


Attaching package: ‘topGO’


The following object is masked from ‘package:IRanges’:

    members

In [2]:
mappingFile = read.table("/workdir/sh2246/p_phyloGWAS/output/OGToPv_mapping.txt")
annualTopHits = read.table("/workdir/sh2246/p_phyloGWAS/output/dnds_topHits.txt",header = T)
annualTopHits2 = read.table("/workdir/sh2246/p_phyloGWAS/output/lifeHistory_topHits.txt",header = T)
annualTopHits3 = read.table("/workdir/sh2246/p_phyloGWAS/output/shared_dnds_lifehistory_topHits.txt",header = T)
topHits = mappingFile[mappingFile[,2]%in%annualTopHits[,1],1]
topHits2 = mappingFile[mappingFile[,2]%in%annualTopHits2[,1],1]
topHits3 = mappingFile[mappingFile[,2]%in%annualTopHits3[,1],1]

In [4]:
GODB <- readMappings("/workdir/sh2246/p_panAndOGASR/data/Pv_GOTable.txt",IDsep = ",")
background = intersect(names(GODB),mappingFile[,1])
# background = names(GODB)

tmp=factor(as.integer(background%in%topHits))
names(tmp)=background
tgd1=new( "topGOdata", ontology="BP", allGenes = tmp, nodeSize=5,annot=annFUN.gene2GO, gene2GO = GODB)
resTopGO.classic=runTest(tgd1, algorithm = "classic", statistic = "Fisher")
resTopGO.weight01=runTest(tgd1, algorithm = "weight01", statistic = "Fisher")
GO_res_table=GenTable(tgd1,Fisher.classic = resTopGO.classic,Fisher.weight01=resTopGO.weight01,orderBy = "Fisher.weight01",ranksOf="Fisher.classic",topNodes=length(resTopGO.classic@score),numChar=100)

tmp=factor(as.integer(background%in%topHits2))
names(tmp)=background
tgd2=new( "topGOdata", ontology="BP", allGenes = tmp, nodeSize=5,annot=annFUN.gene2GO, gene2GO = GODB)
resTopGO.classic=runTest(tgd2, algorithm = "classic", statistic = "Fisher")
resTopGO.weight01=runTest(tgd2, algorithm = "weight01", statistic = "Fisher")
GO_res_table2=GenTable(tgd2,Fisher.classic = resTopGO.classic,Fisher.weight01=resTopGO.weight01,orderBy = "Fisher.weight01",ranksOf="Fisher.classic",topNodes=length(resTopGO.classic@score),numChar=100)

tmp=factor(as.integer(background%in%topHits3))
names(tmp)=background
tgd3=new( "topGOdata", ontology="BP", allGenes = tmp, nodeSize=5,annot=annFUN.gene2GO, gene2GO = GODB)
resTopGO.classic=runTest(tgd3, algorithm = "classic", statistic = "Fisher")
resTopGO.weight01=runTest(tgd3, algorithm = "weight01", statistic = "Fisher")
GO_res_table3=GenTable(tgd3,Fisher.classic = resTopGO.classic,Fisher.weight01=resTopGO.weight01,orderBy = "Fisher.weight01",ranksOf="Fisher.classic",topNodes=length(resTopGO.classic@score),numChar=100)

Building most specific GOs .....

	( 1027 GO terms found. )


Build GO DAG topology ..........

	( 2499 GO terms and 5124 relations. )


Annotating nodes ...............

	( 6237 genes annotated to the GO terms. )


			 -- Classic Algorithm --

		 the algorithm is scoring 399 nontrivial nodes
		 parameters:
			 test statistic: fisher


			 -- Weight01 Algorithm --

		 the algorithm is scoring 399 nontrivial nodes
		 parameters:
			 test statistic: fisher


	 Level 13:	2 nodes to be scored	(0 eliminated genes)


	 Level 12:	5 nodes to be scored	(0 eliminated genes)


	 Level 11:	10 nodes to be scored	(44 eliminated genes)


	 Level 10:	21 nodes to be scored	(145 eliminated genes)


	 Level 9:	42 nodes to be scored	(914 eliminated genes)


	 Level 8:	42 nodes to be scored	(1110 eliminated genes)


	 Level 7:	47 nodes to be scored	(1555 eliminated genes)


	 Level 6:	62 nodes to be scored	(2365 eliminated genes)


	 Level 5:	72 nodes to be scored	(3509 eliminated genes)


	 Level 4:	53 nodes to be scored	(4480 eliminated genes)


	 Level 3:	32 nodes to be scored	(5358 eliminated genes)


	 Level 2:	10 nodes to be scored	(5986 eliminated genes)


	 Level 1:	1 nodes to be scored	(6206 eliminated genes)


Building most specific GOs .....

	( 1027 GO terms found. )


Build GO DAG topology ..........

	( 2499 GO terms and 5124 relations. )


Annotating nodes ...............

	( 6237 genes annotated to the GO terms. )


			 -- Classic Algorithm --

		 the algorithm is scoring 314 nontrivial nodes
		 parameters:
			 test statistic: fisher


			 -- Weight01 Algorithm --

		 the algorithm is scoring 314 nontrivial nodes
		 parameters:
			 test statistic: fisher


	 Level 12:	4 nodes to be scored	(0 eliminated genes)


	 Level 11:	6 nodes to be scored	(0 eliminated genes)


	 Level 10:	9 nodes to be scored	(130 eliminated genes)


	 Level 9:	22 nodes to be scored	(789 eliminated genes)


	 Level 8:	30 nodes to be scored	(881 eliminated genes)


	 Level 7:	37 nodes to be scored	(1322 eliminated genes)


	 Level 6:	53 nodes to be scored	(2089 eliminated genes)


	 Level 5:	63 nodes to be scored	(3244 eliminated genes)


	 Level 4:	48 nodes to be scored	(4265 eliminated genes)


	 Level 3:	31 nodes to be scored	(5211 eliminated genes)


	 Level 2:	10 nodes to be scored	(5956 eliminated genes)


	 Level 1:	1 nodes to be scored	(6192 eliminated genes)


Building most specific GOs .....

	( 1027 GO terms found. )


Build GO DAG topology ..........

	( 2499 GO terms and 5124 relations. )


Annotating nodes ...............

	( 6237 genes annotated to the GO terms. )


			 -- Classic Algorithm --

		 the algorithm is scoring 259 nontrivial nodes
		 parameters:
			 test statistic: fisher


			 -- Weight01 Algorithm --

		 the algorithm is scoring 259 nontrivial nodes
		 parameters:
			 test statistic: fisher


	 Level 12:	2 nodes to be scored	(0 eliminated genes)


	 Level 11:	4 nodes to be scored	(0 eliminated genes)


	 Level 10:	9 nodes to be scored	(65 eliminated genes)


	 Level 9:	17 nodes to be scored	(772 eliminated genes)


	 Level 8:	23 nodes to be scored	(881 eliminated genes)


	 Level 7:	29 nodes to be scored	(1185 eliminated genes)


	 Level 6:	38 nodes to be scored	(1732 eliminated genes)


	 Level 5:	54 nodes to be scored	(2982 eliminated genes)


	 Level 4:	41 nodes to be scored	(3757 eliminated genes)


	 Level 3:	31 nodes to be scored	(5044 eliminated genes)


	 Level 2:	10 nodes to be scored	(5780 eliminated genes)


	 Level 1:	1 nodes to be scored	(6192 eliminated genes)

In [19]:
GO_res_table$sigGenes = sapply(GO_res_table[,1],function(x) {
    paste(mappingFile[mappingFile[,1]%in%intersect(topHits,genesInTerm(tgd1,x)[[1]]),2],collapse = ",")
})

GO_res_table2$sigGenes = sapply(GO_res_table2[,1],function(x) {
    paste(mappingFile[mappingFile[,1]%in%intersect(topHits2,genesInTerm(tgd2,x)[[1]]),2],collapse = ",")
})
GO_res_table3$sigGenes = sapply(GO_res_table3[,1],function(x) {
    paste(mappingFile[mappingFile[,1]%in%intersect(topHits3,genesInTerm(tgd3,x)[[1]]),2],collapse = ",")
})

In [22]:
write.table(GO_res_table,"/workdir/sh2246/p_phyloGWAS/output/GO_dnds_topHits.txt",sep = "\t")
write.table(GO_res_table2,"/workdir/sh2246/p_phyloGWAS/output/GO_lifeHistory_topHits.txt",sep = "\t")
write.table(GO_res_table3,"/workdir/sh2246/p_phyloGWAS/output/GO_shared_dnds_lifehistory_topHits.txt",sep = "\t")

In [ ]:
#end

In [11]:
head(GO_res_table2)

  GO.ID      Term                              Annotated Significant Expected
1 GO:0042938 dipeptide transport                  6       2           0.07
2 GO:0009664 plant-type cell wall organization   20       2           0.24
3 GO:0006793 phosphorus metabolic process      1013      12          12.02
4 GO:0006486 protein glycosylation               71       3           0.84
5 GO:0009640 photomorphogenesis                   6       1           0.07
6 GO:0009959 negative gravitropism                6       1           0.07
  Rank in Fisher.classic Fisher.classic Fisher.weight01
1   1                    0.002          0.002
2   7                    0.023          0.023
3 225                    0.552          0.047
4  11                    0.052          0.052
5  16                    0.069          0.069
6  17                    0.069          0.069

In [17]:
intersect(topHits2,genesInTerm(tgd2,"GO:0042938")[[1]])
mappingFile[mappingFile[,1]%in%intersect(topHits2,genesInTerm(tgd2,"GO:0042938")[[1]]),2]

[1] "Pavag09G155200.1" "Pavag01G487400.1"

[1] "OG0003275" "OG0009540" "OG0021261"

In [20]:
head(GO_res_table)

  GO.ID      Term                                                 Annotated
1 GO:0051668 localization within membrane                          22
2 GO:0016192 vesicle-mediated transport                           171
3 GO:0006488 dolichol-linked oligosaccharide biosynthetic process   5
4 GO:0006559 L-phenylalanine catabolic process                      5
5 GO:0009850 auxin metabolic process                                5
6 GO:0006874 cellular calcium ion homeostasis                       6
  Significant Expected Rank in Fisher.classic Fisher.classic Fisher.weight01
1 2           0.27      2                     0.029          0.024
2 6           2.08      1                     0.017          0.050
3 1           0.06      7                     0.059          0.059
4 1           0.06      8                     0.059          0.059
5 1           0.06      9                     0.059          0.059
6 1           0.07     15                     0.071          0.071
  sigGenes
1 OG0008038,OG0009349,OG0012689
2 OG0004396,OG0008889,OG0010873,OG0012689,OG0015498,OG0017970
3 OG0007863
4 OG0010427,OG0018774,OG0020659
5 OG0009665
6 OG0004993

In [32]:
tmp=factor(as.integer(background%in%topHits_ePC2))
names(tmp)=background
tgd4=new( "topGOdata", ontology="BP", allGenes = tmp, nodeSize=5,annot=annFUN.gene2GO, gene2GO = GODB)
resTopGO.classic=runTest(tgd4, algorithm = "classic", statistic = "Fisher")
resTopGO.weight01=runTest(tgd4, algorithm = "weight01", statistic = "Fisher")
GO_res_table_ePC2=GenTable(tgd4,Fisher.classic = resTopGO.classic,Fisher.weight01=resTopGO.weight01,orderBy = "Fisher.weight01",ranksOf="Fisher.classic",topNodes=length(resTopGO.classic@score),numChar=100)

Building most specific GOs .....

	( 1027 GO terms found. )


Build GO DAG topology ..........

	( 2499 GO terms and 5124 relations. )


Annotating nodes ...............

	( 6237 genes annotated to the GO terms. )


			 -- Classic Algorithm --

		 the algorithm is scoring 102 nontrivial nodes
		 parameters:
			 test statistic: fisher


			 -- Weight01 Algorithm --

		 the algorithm is scoring 102 nontrivial nodes
		 parameters:
			 test statistic: fisher


	 Level 13:	1 nodes to be scored	(0 eliminated genes)


	 Level 12:	1 nodes to be scored	(0 eliminated genes)


	 Level 11:	3 nodes to be scored	(36 eliminated genes)


	 Level 10:	5 nodes to be scored	(36 eliminated genes)


	 Level 9:	9 nodes to be scored	(752 eliminated genes)


	 Level 8:	8 nodes to be scored	(861 eliminated genes)


	 Level 7:	6 nodes to be scored	(869 eliminated genes)


	 Level 6:	14 nodes to be scored	(1409 eliminated genes)


	 Level 5:	22 nodes to be scored	(2292 eliminated genes)


	 Level 4:	18 nodes to be scored	(3130 eliminated genes)


	 Level 3:	10 nodes to be scored	(3707 eliminated genes)


	 Level 2:	4 nodes to be scored	(4447 eliminated genes)


	 Level 1:	1 nodes to be scored	(4851 eliminated genes)

In [35]:
head(ePC2TopHits,17)[,1]

 [1] "OG0006898" "OG0014812" "OG0021996" "OG0014180" "OG0003517" "OG0018587"
 [7] "OG0013341" "OG0011520" "OG0020679" "OG0015460" "OG0010537" "OG0010516"
[13] "OG0004229" "OG0015218" "OG0014738" "OG0016696" "OG0010463"

In [37]:
table(ePC2TopHits[,2]>0)

FALSE  TRUE
 7967  9062