In [ ]:
####ID matching####

In [42]:
gffComp = read.table("/workdir/sh2246/p_phyloGWAS_archived/data/annotations/gffcmp.Zm-B73-REFERENCE-NAM-5.0_helixer.gff.tmap",header = T)

In [43]:
head(gffComp)

  ref_gene_id     ref_id               class_code qry_gene_id  qry_id
1 Zm00001eb000010 Zm00001eb000010_T001 m          _chr1_000001 _chr1_000001.1
2 -               -                    u          _chr1_000002 _chr1_000002.1
3 -               -                    u          _chr1_000003 _chr1_000003.1
4 Zm00001eb000200 Zm00001eb000200_T001 c          _chr1_000004 _chr1_000004.1
5 Zm00001eb000210 Zm00001eb000210_T001 m          _chr1_000005 _chr1_000005.1
6 Zm00001eb000210 Zm00001eb000210_T002 c          _chr1_000006 _chr1_000006.1
  num_exons FPKM TPM cov len  major_iso_id   ref_match_len
1  8        0    0   0   3605 _chr1_000001.1 3615
2 15        0    0   0   3609 _chr1_000002.1 -
3 11        0    0   0   2362 _chr1_000003.1 -
4  1        0    0   0    810 _chr1_000004.1 845
5 17        0    0   0   2863 _chr1_000005.1 3446
6  2        0    0   0   1109 _chr1_000006.1 3465

In [63]:
table(gffComp$class_code)[c("=","c","k","m","n","j")]
sum(table(gffComp$class_code)[c("=","c","k","m","n","j")])

    =     c     k     m     n     j
12960  1788  4442   664   743 11201

[1] 31798

In [64]:
gffComp_filtered = gffComp[gffComp$class_code%in%c("=","c","k","m","n","j"),]

In [66]:
gffComp_filtered[,c(1,4)]

      ref_gene_id     qry_gene_id
1     Zm00001eb000010 _chr1_000001
4     Zm00001eb000200 _chr1_000004
5     Zm00001eb000210 _chr1_000005
6     Zm00001eb000210 _chr1_000006
8     Zm00001eb000220 _chr1_000008
9     Zm00001eb000230 _chr1_000009
10    Zm00001eb000250 _chr1_000010
14    Zm00001eb000340 _chr1_000014
15    Zm00001eb000360 _chr1_000015
16    Zm00001eb000380 _chr1_000016
17    Zm00001eb000390 _chr1_000017
21    Zm00001eb000440 _chr1_000021
23    Zm00001eb000490 _chr1_000023
24    Zm00001eb000570 _chr1_000024
25    Zm00001eb000590 _chr1_000025
26    Zm00001eb000640 _chr1_000026
27    Zm00001eb000650 _chr1_000027
28    Zm00001eb000670 _chr1_000028
29    Zm00001eb000690 _chr1_000029
30    Zm00001eb000710 _chr1_000030
31    Zm00001eb000740 _chr1_000031
32    Zm00001eb000760 _chr1_000032
33    Zm00001eb000770 _chr1_000033
34    Zm00001eb000780 _chr1_000034
35    Zm00001eb000790 _chr1_000035
36    Zm00001eb000820 _chr1_000036
37    Zm00001eb000840 _chr1_000037
38    Zm00001eb000860 _chr1_000038
39    Zm00001eb000870 _chr1_000039
40    Zm00001eb000890 _chr1_000040
⋮     ⋮               ⋮
41762 Zm00001eb442740 _scaf_621_000006
41769 Zm00001eb442780 _scaf_625_000001
41778 Zm00001eb442790 _scaf_640_000001
41779 Zm00001eb442800 _scaf_640_000002
41780 Zm00001eb442810 _scaf_644_000001
41781 Zm00001eb442820 _scaf_644_000002
41795 Zm00001eb442870 _scaf_651_000001
41797 Zm00001eb442850 _scaf_651_000003
41798 Zm00001eb442850 _scaf_651_000004
41799 Zm00001eb442840 _scaf_651_000005
41800 Zm00001eb442880 _scaf_656_000001
41803 Zm00001eb442890 _scaf_659_000001
41804 Zm00001eb442890 _scaf_659_000002
41805 Zm00001eb436380 _scaf_66_000001
41806 Zm00001eb436400 _scaf_66_000002
41823 Zm00001eb442940 _scaf_670_000001
41825 Zm00001eb442960 _scaf_674_000001
41826 Zm00001eb442960 _scaf_674_000002
41827 Zm00001eb442970 _scaf_674_000003
41828 Zm00001eb442980 _scaf_674_000004
41830 Zm00001eb442990 _scaf_675_000002
41837 Zm00001eb443000 _scaf_675_000009
41852 Zm00001eb443030 _scaf_695_000001
41858 Zm00001eb436490 _scaf_72_000006
41862 Zm00001eb436450 _scaf_72_000010
41892 Zm00001eb436880 _scaf_87_000030
41894 Zm00001eb436840 _scaf_87_000032
41896 Zm00001eb436810 _scaf_87_000034
41899 Zm00001eb436800 _scaf_87_000037
41914 Zm00001eb437040 _scaf_94_000008

In [47]:
OG_geneID = read.delim("/workdir/sh2246/p_phyloGWAS/output/OrthoFinder/Results_Jun06/Orthogroups/Orthogroups.tsv",header =T)

In [60]:
head(OG_geneID[OG_geneID$Orthogroup%in%helixer_OG_OGfiltered$Orthogroup,c(1,30)])

   Orthogroup
34 OG0000033
54 OG0000053
60 OG0000059
63 OG0000062
68 OG0000067
71 OG0000070
   Zm.B73.REFERENCE.NAM.5.0.aa
34 _chr10_002195.1, _chr10_002565.1, _chr1_001569.1, _chr1_001570.1, _chr2_001452.1, _chr4_001461.1, _chr4_002695.1, _chr6_000131.1, _chr6_000231.1, _chr6_000232.1, _chr6_003201.1, _chr6_003202.1, _chr6_003203.1, _chr7_002917.1, _chr8_002589.1, _chr9_000976.1, _chr9_002984.1
54 _chr10_000334.1, _chr10_002322.1, _chr10_002323.1, _chr10_002324.1, _chr10_002326.1, _chr4_000347.1, _chr4_000348.1, _chr4_000349.1, _chr4_000350.1, _chr4_000351.1, _chr4_000352.1, _chr4_000353.1, _chr4_000354.1, _chr4_000355.1, _chr4_000356.1, _chr4_000357.1, _chr4_000358.1, _chr4_000359.1, _chr4_000360.1, _chr4_003836.1, _chr4_003837.1, _chr4_003838.1
60 _chr10_002700.1, _chr10_002704.1, _chr1_001871.1, _chr1_005284.1, _chr1_005287.1, _chr1_005288.1, _chr2_001256.1, _chr4_000272.1, _chr4_000275.1, _chr4_001491.1, _chr4_001492.1, _chr4_002455.1, _chr4_003894.1, _chr4_004008.1, _chr6_001971.1, _chr6_001972.1, _chr6_001973.1, _chr6_001974.1, _chr8_000948.1, _chr9_000952.1, _chr9_002191.1
63 _chr10_000749.1, _chr10_000766.1, _chr1_000925.1, _chr2_004126.1, _chr2_004136.1, _chr2_004233.1, _chr3_002971.1, _chr3_003381.1, _chr3_003976.1, _chr4_000760.1, _chr5_001621.1, _chr5_003139.1, _chr6_000448.1, _chr6_003046.1, _chr8_002062.1, _chr9_000222.1, _chr9_000324.1
68 _chr2_002576.1, _chr7_000060.1, _chr7_002889.1, _chr7_003124.1
71 _chr10_000118.1, _chr10_000242.1, _chr10_000753.1, _chr10_000754.1, _chr10_000755.1, _chr10_000756.1, _chr10_000757.1, _chr10_000758.1, _chr10_000759.1, _chr10_001929.1, _chr10_002559.1, _chr2_004137.1, _chr3_000264.1, _chr7_001101.1

In [61]:
sum(helixer_OG_OGfiltered$Zm.B73.REFERENCE.NAM.5.0.aa)

[1] 31678

In [71]:
library(dplyr)
library(tidyr)

df1_long <- OG_geneID[OG_geneID$Orthogroup%in%helixer_OG_OGfiltered$Orthogroup,c(1,30)] %>%
  separate_rows(Zm.B73.REFERENCE.NAM.5.0.aa, sep = ",") %>%
  # Trim any extra spaces after splitting
  mutate(helixerID = trimws(Zm.B73.REFERENCE.NAM.5.0.aa))
df_joined <- df1_long %>%
  left_join(gffComp_filtered[,c(1,5)], 
            by = c("helixerID" = "qry_id"))

In [96]:
head(df_joined)

  Orthogroup Zm.B73.REFERENCE.NAM.5.0.aa helixerID       ref_gene_id
1 OG0000033  _chr10_002195.1             _chr10_002195.1 NA
2 OG0000033   _chr10_002565.1            _chr10_002565.1 Zm00001eb407630
3 OG0000033   _chr1_001569.1             _chr1_001569.1  Zm00001eb034240
4 OG0000033   _chr1_001570.1             _chr1_001570.1  Zm00001eb034240
5 OG0000033   _chr2_001452.1             _chr2_001452.1  Zm00001eb097070
6 OG0000033   _chr4_001461.1             _chr4_001461.1  Zm00001eb197310

In [82]:
df_concatenated <- df_joined[,-2] %>%
  group_by(Orthogroup) %>%
  summarise(
    helixer_ids = paste(helixerID, collapse = ","),
    refGene_ids = paste(na.omit(ref_gene_id), collapse = ",")
  )

In [90]:
head(df_concatenated[,-2])

  Orthogroup
1 OG0000033
2 OG0000053
3 OG0000059
4 OG0000062
5 OG0000067
6 OG0000070
  refGene_ids
1 Zm00001eb407630,Zm00001eb034240,Zm00001eb034240,Zm00001eb097070,Zm00001eb197310,Zm00001eb197140,Zm00001eb265890,Zm00001eb265890,Zm00001eb265900,Zm00001eb265880,Zm00001eb265850,Zm00001eb304540,Zm00001eb355410,Zm00001eb392870,Zm00001eb375640
2 Zm00001eb413180,Zm00001eb413260,Zm00001eb413250,Zm00001eb413210,Zm00001eb413190,Zm00001eb171520,Zm00001eb171530,Zm00001eb171540,Zm00001eb171550,Zm00001eb171570,Zm00001eb171580,Zm00001eb171590,Zm00001eb171600,Zm00001eb171610,Zm00001eb171630,Zm00001eb171640,Zm00001eb171650,Zm00001eb171660,Zm00001eb171510,Zm00001eb171500,Zm00001eb171490
3 Zm00001eb405180,Zm00001eb405160,Zm00001eb040570,Zm00001eb018660,Zm00001eb018640,Zm00001eb092770,Zm00001eb169520,Zm00001eb198140,Zm00001eb198150,Zm00001eb202200,Zm00001eb170590,Zm00001eb168290,Zm00001eb292890,Zm00001eb292880,Zm00001eb292850,Zm00001eb292840,Zm00001eb353110,Zm00001eb392340
4 Zm00001eb422190,Zm00001eb422440,Zm00001eb018990,Zm00001eb083380,Zm00001eb083310,Zm00001eb081270,Zm00001eb146770,Zm00001eb137500,Zm00001eb123830,Zm00001eb181740,Zm00001eb244680,Zm00001eb243130,Zm00001eb271240,Zm00001eb269650,Zm00001eb376150,Zm00001eb378250
5 Zm00001eb117940,Zm00001eb299100,Zm00001eb305290,Zm00001eb299090
6 Zm00001eb411220,Zm00001eb422250,Zm00001eb422270,Zm00001eb422290,Zm00001eb422330,Zm00001eb407700,Zm00001eb083290,Zm00001eb123820,Zm00001eb321390

In [103]:
OGtoZm_gffComp = df_concatenated[,-2]
colnames(OGtoZm_gffComp) = c("OGID","ZmID")

In [111]:
sum(!df_concatenated$helixer_ids=="")
sum(!df_concatenated$refGene_ids=="")

[1] 17869

[1] 16992

In [105]:
write.table(OGtoZm_gffComp, "/workdir/sh2246/p_phyloGWAS/output/OGtoZmID_gffComp_20250331.txt",sep = "\t",quote = F,row.names = F,col.names = T)

In [85]:
OGtoZmID = read.table("/workdir/sh2246/p_phyloGWAS/data/OGToZm_mapping_v2.txt")

In [87]:
OGtoZmID$V3 = substr(OGtoZmID$V1,1,15)

In [89]:
head(OGtoZmID[,2:3])

  V2        V3
1 OG0000508 Zm00001eb037000
2 OG0000556 Zm00001eb061630
3 OG0000574 Zm00001eb377400
4 OG0000687 Zm00001eb324180
5 OG0000727 Zm00001eb102900
6 OG0000787 Zm00001eb406740

In [92]:
matchCount = 0
for(i in 1:nrow(OGtoZmID)){
    matchCount = matchCount + as.numeric(any(df_joined[df_joined[,1]%in%OGtoZmID[i,2],4]==OGtoZmID[i,3],na.rm = T))
}

In [100]:
# Create a unique key for each row in df_joined
matches <- paste(df_joined$Orthogroup, df_joined$ref_gene_id, sep = "_")

# Create a key for each row in OGtoZmID
target <- paste(OGtoZmID$V2, OGtoZmID$V3, sep = "_")

# Calculate the match count, counting each OGtoZmID row that has a matching key in df_joined
matchCount <- sum(target %in% matches)

In [102]:
matchCount/length(unique(OGtoZmID$V3))

[1] 0.9017872

In [58]:
which(colnames(OG_geneID)%in%"Zm.B73.REFERENCE.NAM.5.0.aa")

[1] 30