In [37]:
rm(list=ls())
library(Biostrings)
library(parallel)
library(limma)
library(rtracklayer)

In [14]:
trslTab = data.table::fread("/workdir/sh2246/p_phyloGWAS/output/seqIDmapping.txt")

In [38]:
trslTab = data.table::fread("/workdir/sh2246/p_phyloGWAS/output/seqIDmapping_additionalOGs.txt")

In [39]:
trslTab$mapID = paste(trslTab$MPID,gsub(".fa","",trslTab$inputFile),sep = ":")

In [40]:
head(trslTab)

  MPID     inputFile       UniqueID                 mapID
1 MP000001 AN21TSTL0253.fa OG0000062:AN21TSTL0253:0 MP000001:AN21TSTL0253
2 MP000002 AN21TSTL0253.fa OG0000062:AN21TSTL0253:1 MP000002:AN21TSTL0253
3 MP000003 AN21TSTL0253.fa OG0000062:AN21TSTL0253:2 MP000003:AN21TSTL0253
4 MP000004 AN21TSTL0253.fa OG0000062:AN21TSTL0253:3 MP000004:AN21TSTL0253
5 MP000005 AN21TSTL0253.fa OG0000062:AN21TSTL0253:4 MP000005:AN21TSTL0253
6 MP000006 AN21TSTL0253.fa OG0000062:AN21TSTL0253:5 MP000006:AN21TSTL0253

In [19]:
gffFlist = list.files("/workdir/sh2246/p_phyloGWAS/output/orthofinderMiniProt",full.names = T)

In [41]:
gffFlist = list.files("/workdir/sh2246/p_phyloGWAS/output/orthofinderMiniProt_additionalOGs",full.names = T)

In [42]:
FSSeq = unlist(mclapply(gffFlist,function(x){
    gffTest = readGFF(x)
    tmp = gffTest[gffTest$type %in% "mRNA",]
    return(paste(tmp$ID[!is.na(tmp$Frameshift)],gsub('.gff','',strsplit2(x,"/")[,7]),sep = ":"))
},mc.cores = 20))

In [43]:
length(FSSeq)
nrow(trslTab)

[1] 168427

[1] 2113102

In [44]:
outTab = trslTab[,3:4]
outTab$Frameshift = as.numeric(outTab$mapID%in%FSSeq)

In [45]:
head(outTab)

  UniqueID                 mapID                 Frameshift
1 OG0000062:AN21TSTL0253:0 MP000001:AN21TSTL0253 0
2 OG0000062:AN21TSTL0253:1 MP000002:AN21TSTL0253 0
3 OG0000062:AN21TSTL0253:2 MP000003:AN21TSTL0253 0
4 OG0000062:AN21TSTL0253:3 MP000004:AN21TSTL0253 0
5 OG0000062:AN21TSTL0253:4 MP000005:AN21TSTL0253 0
6 OG0000062:AN21TSTL0253:5 MP000006:AN21TSTL0253 0

In [46]:
table(outTab$Frameshift)

      0       1
1944850  168252

In [47]:
data.table::fwrite(outTab,"/workdir/sh2246/p_phyloGWAS/output/frameShiftMutation_additionalOGs.txt",sep = "\t")